CREATE ROLE demo WITH 
    NOSUPERUSER
    CREATEDB
    NOCREATEROLE
    NOINHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1
    PASSWORD 'your_password';

CREATE DATABASE demo OWNER demo;